name: Run Tests

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Echo client payload
        run: echo ${{ toJson(github.event.client_payload) }}
